services: 
   python:
     restart: always 
     build: . 
     container_name: 'python-env' 
     working_dir: '/root/' 
     tty: true 
     depends_on: 
       - mongodb
     volumes: 
       - ./code:/root/code

   mongodb: 
     image: mongo:latest
     ports: 
       - "27017:27017"


